import AppKit
import CryptoKit
import UniformTypeIdentifiers

/// A snapshot of clipboard contents captured from `NSPasteboard`.
struct CapturedClip {
    var kind: ClipKind
    var contentHash: String
    var text: String?
    var rtfData: Data?
    var htmlString: String?
    var imageData: Data?
    var thumbnailData: Data?
    var rawFlavors: Data?
    var fileURLString: String?
    var sourceAppName: String?
    var sourceAppBundleID: String?
    var tags: [SmartTag] = []
}

/// Reads the richest available representation from an `NSPasteboard`.
enum PasteboardReader {
    /// Pasteboard markers used by password managers / clipboard tools to opt out
    /// of clipboard history. We honor all three.
    private static let concealedTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType")
    ]

    /// Builds a `CapturedClip` for the current pasteboard contents, or `nil` if
    /// there is nothing worth storing or the content is marked concealed.
    static func read(_ pasteboard: NSPasteboard) -> CapturedClip? {
        let types = pasteboard.types ?? []
        if concealedTypes.contains(where: types.contains) { return nil }

        let front = NSWorkspace.shared.frontmostApplication
        let appName = front?.localizedName
        let bundleID = front?.bundleIdentifier

        // Capture every flavor for byte-perfect paste (bounded by a size cap).
        let rawFlavors = PasteboardFlavors.capture(pasteboard)

        // 1. Image (only if there's no accompanying text — many text copies also
        //    carry a TIFF rendering we don't want to treat as an image).
        let plain = pasteboard.string(forType: .string)
        if (plain?.isEmpty ?? true), let rawImage = readImage(pasteboard) {
            let display = ImageProcessing.cappedPNG(from: rawImage)
            return CapturedClip(
                kind: .image,
                contentHash: hash(rawImage),
                imageData: display,
                thumbnailData: ImageProcessing.thumbnail(from: display),
                rawFlavors: rawFlavors,
                sourceAppName: appName,
                sourceAppBundleID: bundleID
            )
        }

        // 2. File URL(s).
        if let urls = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], let url = urls.first {
            let joined = urls.map(\.absoluteString).joined(separator: "\n")
            return CapturedClip(
                kind: .file,
                contentHash: hash(joined),
                text: urls.map(\.path).joined(separator: "\n"),
                rawFlavors: rawFlavors,
                fileURLString: url.absoluteString,
                sourceAppName: appName,
                sourceAppBundleID: bundleID
            )
        }

        guard let text = plain, !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else {
            return nil
        }

        // 3. Styled / HTML text — preserved so it pastes with formatting.
        let rtf = pasteboard.data(forType: .rtf)
        let html = pasteboard.data(forType: .html).flatMap { String(data: $0, encoding: .utf8) }
        let isRich = (rtf != nil) || (html != nil)

        return CapturedClip(
            kind: isRich ? .richText : .text,
            contentHash: hash(text),
            text: text,
            rtfData: rtf,
            htmlString: html,
            rawFlavors: rawFlavors,
            sourceAppName: appName,
            sourceAppBundleID: bundleID
        )
    }

    // MARK: Helpers

    private static func readImage(_ pasteboard: NSPasteboard) -> Data? {
        if let png = pasteboard.data(forType: .png) { return png }
        // Normalize TIFF → PNG for compact, consistent storage.
        if let tiff = pasteboard.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff),
           let png = rep.representation(using: .png, properties: [:]) {
            return png
        }
        return nil
    }

    private static func hash(_ string: String) -> String {
        hash(Data(string.utf8))
    }

    private static func hash(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
